[rules]
max_file_tokens = 1500
max_cognitive_complexity = 15
max_nesting_depth = 3
max_function_args = 4
max_function_words = 10
max_lcom4 = 1
min_ahf = 60.0
max_cbo = 9
max_sfout = 7
ignore_naming_on = []
ignore_tokens_on = [
    "Cargo.lock",
    "package-lock.json",
    "README.md",
    "docs",
    "target",
    "vendor",
]

[rules.safety]
require_safety_comment = true
ban_unsafe = false

[rules.locality]
max_distance = 2
l1_threshold = 2
hub_threshold = 1.0
min_hub_afferent = 5
god_module_threshold = 20
deadwood_threshold = 2
mode = "error"
exempt_patterns = []

[preferences]
auto_copy = true
auto_format = false
system_bell = false
backup_retention = 5
progress_bars = true
require_plan = true
write_fix_packet = false
fix_packet_path = "slopchop-fixme.txt"
auto_promote = true

[commands]
fix = ["cargo fmt"]
check = [
    "cargo clippy --all-targets -- -D warnings -W clippy::pedantic -W clippy::unwrap_used -W clippy::expect_used -W clippy::indexing_slicing -A clippy::struct_excessive_bools -A clippy::module_name_repetitions -A clippy::missing_errors_doc -A clippy::must_use_candidate",
    "cargo test",
]
